spacing         = 0
padding         = 0
separator       = " "
key_color       = "Blue"
separator_color = "White"
hide_ascii      = true 

[bar]
visible         = false 

[box.inner_margin]
x               = 0
y               = 0
