#---------------------------------------------------------------------------------------------------------------------
#	THEME/COLORS
#---------------------------------------------------------------------------------------------------------------------
[colors]
transparent_background_colors = true

[colors.primary]
background = "#1F1F1F"
foreground = "#D4D4D4"

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

#---------------------------------------------------------------------------------------------------------------------
#	FONT SETTINGS
#---------------------------------------------------------------------------------------------------------------------
[font]
size = 16
normal = { family = "Hasklug Nerd Font Mono", style = "Light" }
bold = { family = "Hasklug Nerd Font Mono", style = "Medium" }
italic = { family = "Hasklug Nerd Font Mono", style = "Italic" }

#---------------------------------------------------------------------------------------------------------------------
#	WINDOW SETTINGS
#---------------------------------------------------------------------------------------------------------------------
[window]
decorations = "buttonless"
opacity = 0.9
blur  = true

[window.padding]
x = 28
y = 48

#---------------------------------------------------------------------------------------------------------------------
#	KEYBOARD MAPPINGS
#---------------------------------------------------------------------------------------------------------------------
[keyboard]
bindings = [
	{ key = "Left", mods = "Alt", chars = "\u001bB" },
	{ key = "Right", mods = "Alt", chars = "\u001bF" },
	{ key = "Left", mods = "Command", chars = "\u001bOH" },
	{ key = "Right", mods = "Command", chars = "\u001bOF" },
	{ key = "Back", mods = "Command", chars = "\u0015" },
]
